### ISSUE TITLE
Following the installation instructions leads to hard-to-debug RDBMS auth errors

### ISSUE THREAD

**Issue by dnet** [byro/byro#219]
Following [the official installation docs](https://byro.readthedocs.io/en/latest/administrator/installation/) results in Byro being installed using `pip`, which (as of today, 2021-12-02) installs a version that contains a `local_settings.py` with a database configuration, yet the installation instructions describe using `/etc/byro/byro.cfg`. And since `local_settings.py` overrides `byro.cfg` and the installation instructions don't even mention `local_settings.py` I just scratched my head trying to debug why `migrate` fails with `FATAL:  password authentication failed for user "byro"` when I specified the proper password in `byro.cfg` as asked by the instructions.

There's of course a little hint in the first line saying `You are using the deprecated local_settings.py – Please move to the byro.cfg format.`, but that pretty much only makes sense in retrospect and it gets scrolled out anyways because of the long stack trace caused by the failed authentication.

**Comment by rixx** [comment]
Thank you for the note – the release never saw much use, I think, as most people installed from source. I pushed a new release, and updated the documentation mentioning that option.

**Comment by dnet** [comment]
Thanks for the changes, what will trigger the update on the https://byro.readthedocs.io/en/latest/administrator/installation/ page? I still see the original version there.

**Comment by rixx** [comment]
The rtd build was broken, fixed now.
